# Generated by Django 4.0.3 on 2022-04-12 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryproduct",
            name="meeasure_unit",
        ),
        migrations.RemoveField(
            model_name="historicalcategoryproduct",
            name="meeasure_unit",
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="category_product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.categoryproduct",
                verbose_name="Categoria de producto",
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="measure_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categoryproduct",
                verbose_name="Categoria de producto",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measure_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
    ]
