exclude: "docs|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^assets/vendor/
      - id: end-of-file-fixer
        exclude: ^assets/vendor/
      - id: check-yaml
        exclude: ^assets/vendor/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [pep8-naming, flake8-bugbear]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests]
        files: .py$

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.930
  #   hooks:
  #   -   id: mypy
  #       verbose: true
  #       additional_dependencies: [ "django-stubs==1.9.0"]
  #       entry: bash -c 'mypy "$@" || true' --

  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       args: ["."]
